import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/Widgets";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Outist | Professionale",
  description: "Generated by dravyafolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href={inter.href} />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
